name: Automated Regressive Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: 'Ambiente dos Testes'
        required: true
        default: 'prod'
        type: choice
        options:
          - dev
          - hml
          - prod

jobs:
  regressive_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Environment Variable
        run: echo "ENVIRONMENT=${{ github.event.inputs.environment || 'prod' }}" >> $GITHUB_ENV

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Running Regressive Tests
        run: |
          echo "Environment: $ENVIRONMENT"
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          rfbrowser init
          python -m robot -d regressive_tests -v ENVIRONMENT:$ENVIRONMENT tests
        continue-on-error: true 

      - name: Publish Artifacts
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: regressive_tests
          path: regressive_tests/*